package proyekpbd;

import java.awt.Container;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sidhat
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    private final Connection con;
    private final Statement stat;
    private ResultSet rs;
    private String sql;
    
    public Login() throws SQLException {
        initComponents();
        setResizable(false);
        Koneksi DB = new Koneksi ();
        DB.bukaKoneksi();
        con =DB.con;
        stat = DB.stm;
        txtusername.requestFocus();
    }

    public boolean validasi() 
    {
        String username, password;
        username=txtusername.getText();
        password=txtpassword.getText();
        if (username.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter the Username");
            return false;
        }
        if(password.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter the Password");
            return false;
        }
    return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgbiru = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        bgputih = new javax.swing.JPanel();
        LoginBtn = new java.awt.Button();
        lbllogin = new javax.swing.JLabel();
        txtusername = new javax.swing.JFormattedTextField();
        txtpassword = new javax.swing.JPasswordField();
        lblpasswors = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgbiru.setBackground(new java.awt.Color(0, 153, 255));
        bgbiru.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sidhat\\Pictures\\Image\\lock.png")); // NOI18N
        bgbiru.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 260, 290));

        getContentPane().add(bgbiru, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 480));

        bgputih.setBackground(new java.awt.Color(255, 255, 255));
        bgputih.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginBtn.setBackground(new java.awt.Color(0, 153, 255));
        LoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setLabel("Login");
        LoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBtnMouseClicked(evt);
            }
        });
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        bgputih.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 130, 40));

        lbllogin.setBackground(new java.awt.Color(255, 255, 255));
        lbllogin.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lbllogin.setForeground(new java.awt.Color(0, 153, 255));
        lbllogin.setText("LOGIN");
        bgputih.add(lbllogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 90, 40));
        bgputih.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 220, 40));
        bgputih.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 220, 40));

        lblpasswors.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblpasswors.setText("Password");
        bgputih.add(lblpasswors, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 80, 40));

        lblusername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblusername.setText("Username");
        bgputih.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 80, 40));

        getContentPane().add(bgputih, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 530, 480));

        setSize(new java.awt.Dimension(923, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        try {
                sql = "SELECT * FROM tb_kasir WHERE id_kasir='" + txtusername.getText() + "' AND password='" + txtpassword.getText() + "'";
                rs = stat.executeQuery(sql);
                if (rs.next()) {
                    if (txtusername.getText().equals(rs.getString("id_kasir")) && txtpassword.getText().equals(rs.getString("password"))) {
  
                        JOptionPane.showMessageDialog(null, "Berhasil Login");
                        this.dispose();
                        new Dashboard().setVisible(true);
                    }
                } else {
                    txtusername.setText("");
                    txtusername.requestFocus();
                    txtpassword.setText("");
                    JOptionPane.showMessageDialog(null, "ID atau Password Salah", "Infomasi", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void LoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseClicked
        
    }//GEN-LAST:event_LoginBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button LoginBtn;
    private javax.swing.JPanel bgbiru;
    private javax.swing.JPanel bgputih;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JLabel lblpasswors;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JFormattedTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
