/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyekpbd;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sidhat
 */
public class Logout extends javax.swing.JFrame {

    /**
     * Creates new form Logout
     */
    public Logout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlLogout2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btntidak = new java.awt.Button();
        btnya = new java.awt.Button();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLogout2.setBackground(new java.awt.Color(102, 204, 255));
        pnlLogout2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apakah anda yakin ingin keluar ?");
        pnlLogout2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 500, -1));

        btntidak.setBackground(new java.awt.Color(255, 255, 255));
        btntidak.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btntidak.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btntidak.setLabel("TIDAK");
        btntidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntidakActionPerformed(evt);
            }
        });
        pnlLogout2.add(btntidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 70, 30));

        btnya.setBackground(new java.awt.Color(255, 255, 255));
        btnya.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnya.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnya.setLabel("YA");
        btnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyaActionPerformed(evt);
            }
        });
        pnlLogout2.add(btnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogout2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogout2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntidakActionPerformed
        Dashboard xx = null;
        try {
            xx = new Dashboard();
        } catch (SQLException ex) {
            Logger.getLogger(Logout.class.getName()).log(Level.SEVERE, null, ex);
        }
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btntidakActionPerformed

    private void btnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnyaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btntidak;
    private java.awt.Button btnya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlLogout2;
    // End of variables declaration//GEN-END:variables
}
