package proyekpbd;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Sidhat
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form transaksi
     */
    public Transaksi() {
        initComponents();
        tanggal();
                
        txtharga.setText("Rp. ");
        txtsubtotal.setText("Rp. ");
        txttotal.setText("Rp. ");
        txtbayar.setText("Rp. ");
        txtkembali.setText("Rp. ");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnldashboard = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pnlbarang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlkasir = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlsupplier = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnllaporan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnllogout = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblharga = new javax.swing.JLabel();
        lblnamabarang = new javax.swing.JLabel();
        lblkembali = new javax.swing.JLabel();
        lbltanggal = new javax.swing.JLabel();
        lblnonota = new javax.swing.JLabel();
        lblsubtotal = new javax.swing.JLabel();
        lblkuantitas = new javax.swing.JLabel();
        txtkodebarang = new javax.swing.JTextField();
        txtnonota = new javax.swing.JTextField();
        txtnamabarang = new javax.swing.JTextField();
        txttanggal = new javax.swing.JTextField();
        txtsubtotal = new javax.swing.JTextField();
        txtkembali = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        spinnerkuantitas = new javax.swing.JSpinner();
        txttotal = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        lblkodebarang = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        lblbayar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnselesai = new javax.swing.JButton();
        btnctknota = new javax.swing.JButton();
        btnbatalkan = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        panelDashboard = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(0, 153, 255));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel5.setBackground(new java.awt.Color(102, 204, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidepane.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Toko N3 Jaya");
        sidepane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, 40));

        pnldashboard.setBackground(new java.awt.Color(0, 204, 255));
        pnldashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnldashboardMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DASHBOARD");

        javax.swing.GroupLayout pnldashboardLayout = new javax.swing.GroupLayout(pnldashboard);
        pnldashboard.setLayout(pnldashboardLayout);
        pnldashboardLayout.setHorizontalGroup(
            pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldashboardLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnldashboardLayout.setVerticalGroup(
            pnldashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidepane.add(pnldashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 40));

        pnlbarang.setBackground(new java.awt.Color(0, 204, 255));
        pnlbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlbarangMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATA BARANG");

        javax.swing.GroupLayout pnlbarangLayout = new javax.swing.GroupLayout(pnlbarang);
        pnlbarang.setLayout(pnlbarangLayout);
        pnlbarangLayout.setHorizontalGroup(
            pnlbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlbarangLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlbarangLayout.setVerticalGroup(
            pnlbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidepane.add(pnlbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 40));

        pnlkasir.setBackground(new java.awt.Color(0, 204, 255));
        pnlkasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlkasirMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA KASIR");

        javax.swing.GroupLayout pnlkasirLayout = new javax.swing.GroupLayout(pnlkasir);
        pnlkasir.setLayout(pnlkasirLayout);
        pnlkasirLayout.setHorizontalGroup(
            pnlkasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlkasirLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlkasirLayout.setVerticalGroup(
            pnlkasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidepane.add(pnlkasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 40));

        pnlsupplier.setBackground(new java.awt.Color(0, 204, 255));
        pnlsupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlsupplierMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DATA SUPPLIER");

        javax.swing.GroupLayout pnlsupplierLayout = new javax.swing.GroupLayout(pnlsupplier);
        pnlsupplier.setLayout(pnlsupplierLayout);
        pnlsupplierLayout.setHorizontalGroup(
            pnlsupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlsupplierLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlsupplierLayout.setVerticalGroup(
            pnlsupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidepane.add(pnlsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, 40));

        pnllaporan.setBackground(new java.awt.Color(0, 204, 255));
        pnllaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnllaporanMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LAPORAN");

        javax.swing.GroupLayout pnllaporanLayout = new javax.swing.GroupLayout(pnllaporan);
        pnllaporan.setLayout(pnllaporanLayout);
        pnllaporanLayout.setHorizontalGroup(
            pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllaporanLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnllaporanLayout.setVerticalGroup(
            pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidepane.add(pnllaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, 40));

        pnllogout.setBackground(new java.awt.Color(0, 204, 255));
        pnllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnllogoutMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LOG OUT");

        javax.swing.GroupLayout pnllogoutLayout = new javax.swing.GroupLayout(pnllogout);
        pnllogout.setLayout(pnllogoutLayout);
        pnllogoutLayout.setHorizontalGroup(
            pnllogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllogoutLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnllogoutLayout.setVerticalGroup(
            pnllogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidepane.add(pnllogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, 40));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 680));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        jLabel9.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TRANSAKSI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 790, 110));

        lblharga.setText("Harga (Rp.)");
        bg.add(lblharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 100, 20));

        lblnamabarang.setText("Nama barang");
        bg.add(lblnamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 100, 20));

        lblkembali.setText("Kembali (Rp.)");
        bg.add(lblkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 100, 30));

        lbltanggal.setText("Tanggal");
        bg.add(lbltanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 90, 20));

        lblnonota.setText("No. nota");
        bg.add(lblnonota, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 120, 100, 20));

        lblsubtotal.setText("Sub-total");
        bg.add(lblsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 100, 20));

        lblkuantitas.setText("Kuantitas");
        bg.add(lblkuantitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 100, 20));

        txtkodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodebarangActionPerformed(evt);
            }
        });
        bg.add(txtkodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 100, -1));

        txtnonota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnonotaActionPerformed(evt);
            }
        });
        bg.add(txtnonota, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 220, -1));

        txtnamabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamabarangActionPerformed(evt);
            }
        });
        bg.add(txtnamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 220, -1));

        txttanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanggalActionPerformed(evt);
            }
        });
        bg.add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 220, -1));

        txtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtotalActionPerformed(evt);
            }
        });
        bg.add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 220, -1));

        txtkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembaliActionPerformed(evt);
            }
        });
        bg.add(txtkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 220, 30));

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        bg.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 220, -1));

        spinnerkuantitas.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 0));
        spinnerkuantitas.setAutoscrolls(true);
        spinnerkuantitas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bg.add(spinnerkuantitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 270, 50, -1));

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        bg.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 220, 30));

        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        bg.add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 220, 30));

        lblkodebarang.setText("Kode barang");
        bg.add(lblkodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 180, 100, 20));

        lbltotal.setText("Total (Rp.)");
        bg.add(lbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 100, 30));

        lblbayar.setText("Bayar (Rp.)");
        bg.add(lblbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Kode barang", "Nama barang", "Harga", "Kuantitas", "Sub-total", "Aksi"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 730, 290));

        btnselesai.setText("Selesai");
        btnselesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselesaiActionPerformed(evt);
            }
        });
        bg.add(btnselesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 90, 40));

        btnctknota.setText("Cetak nota");
        btnctknota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnctknotaActionPerformed(evt);
            }
        });
        bg.add(btnctknota, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 90, 40));

        btnbatalkan.setText("Batalkan");
        btnbatalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalkanActionPerformed(evt);
            }
        });
        bg.add(btnbatalkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        bg.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        bg.add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 60, -1));

        panelDashboard.setBackground(new java.awt.Color(0, 204, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DASHBOARD");

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDashboardLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodebarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodebarangActionPerformed

    private void txtnonotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnonotaActionPerformed
        
    }//GEN-LAST:event_txtnonotaActionPerformed

    private void txtnamabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamabarangActionPerformed

    private void txttanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttanggalActionPerformed

    private void txtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubtotalActionPerformed

    private void txtkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembaliActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarActionPerformed

    private void btnselesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselesaiActionPerformed
        int harga = Integer.parseInt(txtharga.getText());
        int jumlah = Integer.parseInt((String) spinnerkuantitas.getValue());
        int total = (harga * jumlah);
        txttotal.setText(Integer.toString(total));
        
        txtsubtotal.setText("Rp. ");
        txtkodebarang.setText("");
        txtnamabarang.setText("");
        txtharga.setText("Rp. ");
        txtsubtotal.setText("Rp. ");
        spinnerkuantitas.setValue(0);
        
        
        
    }//GEN-LAST:event_btnselesaiActionPerformed

    private void btnctknotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnctknotaActionPerformed
        
    }//GEN-LAST:event_btnctknotaActionPerformed

    private void btnbatalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalkanActionPerformed
        txtkodebarang.setText("");
        txtnamabarang.setText("");
        txtharga.setText("Rp. ");
        txtsubtotal.setText("Rp. ");
        spinnerkuantitas.setValue(0);
        
    }//GEN-LAST:event_btnbatalkanActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        txtkodebarang.setText("");
        txtnamabarang.setText("");
        txtharga.setText("Rp. ");
        txtsubtotal.setText("Rp. ");
        spinnerkuantitas.setValue(0);
    }//GEN-LAST:event_btntambahActionPerformed

    private void pnldashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnldashboardMouseClicked
        Dashboard xx = null;
        try {
            xx = new Dashboard();
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnldashboardMouseClicked

    private void pnlbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlbarangMouseClicked
        DataBarang xx = null;
        try {
            xx = new DataBarang();
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlbarangMouseClicked

    private void pnlkasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlkasirMouseClicked
        DataKasir xx = null;
        try {
            xx = new DataKasir();
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlkasirMouseClicked

    private void pnlsupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlsupplierMouseClicked
        DataSupplier xx = null;
        try {
            xx = new DataSupplier();
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlsupplierMouseClicked

    private void pnllaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllaporanMouseClicked
        Laporan xx;
        xx = new Laporan();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnllaporanMouseClicked

    private void pnllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllogoutMouseClicked
        Logout xx;
        xx = new Logout();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnllogoutMouseClicked

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    public void tanggal(){
    Thread p=new Thread(){
        public void run(){
            for(;;){
                
                    Calendar cal = new GregorianCalendar();
                    int hari = cal.get(Calendar.DAY_OF_MONTH);
                    int bulan = cal.get(Calendar.MONTH);
                    int tahun = cal.get(Calendar.YEAR);
                    txttanggal.setText(hari+"/"+bulan+"/"+tahun);
                    }
                }
        };
    p.start();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnbatalkan;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnctknota;
    private javax.swing.JButton btnselesai;
    private javax.swing.JButton btntambah;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblbayar;
    private javax.swing.JLabel lblharga;
    private javax.swing.JLabel lblkembali;
    private javax.swing.JLabel lblkodebarang;
    private javax.swing.JLabel lblkuantitas;
    private javax.swing.JLabel lblnamabarang;
    private javax.swing.JLabel lblnonota;
    private javax.swing.JLabel lblsubtotal;
    private javax.swing.JLabel lbltanggal;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel pnlbarang;
    private javax.swing.JPanel pnldashboard;
    private javax.swing.JPanel pnlkasir;
    private javax.swing.JPanel pnllaporan;
    private javax.swing.JPanel pnllogout;
    private javax.swing.JPanel pnlsupplier;
    private javax.swing.JPanel sidepane;
    private javax.swing.JSpinner spinnerkuantitas;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkembali;
    private javax.swing.JTextField txtkodebarang;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtnonota;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
